# -*- coding: utf-8 -*-
"""User Retention Cohort Analysis for E-commerce Platform

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CUq54kStYJ62ISzyxJL96CN0QRttZt0Y
"""

from google.colab import files
uploaded=files.upload()

!unzip /content/olist_customers_dataset.csv.zip

!unzip /content/olist_orders_dataset.csv.zip

import pandas as pd
orders=pd.read_csv('/content/olist_orders_dataset.csv')
orders.head()

customers=pd.read_csv('/content/olist_customers_dataset.csv')
customers.head()

df = pd.merge(orders, customers, on="customer_id")

df.head()

df = df[['customer_unique_id', 'order_purchase_timestamp']]

df['order_purchase_timestamp'] = pd.to_datetime(df['order_purchase_timestamp'])

df = df.dropna()

df['order_month'] = df['order_purchase_timestamp'].dt.to_period('M')

df['cohort_month'] = df.groupby('customer_unique_id')['order_purchase_timestamp']\
                      .transform('min')\
                      .dt.to_period('M')

df['cohort_index'] = (df['order_month'] - df['cohort_month']).apply(lambda x: x.n)

cohort_data = df.groupby(['cohort_month', 'cohort_index'])['customer_unique_id']\
                .nunique()\
                .reset_index()

cohort_pivot = cohort_data.pivot(index='cohort_month',
                                columns='cohort_index',
                                values='customer_unique_id')

cohort_retention = cohort_pivot.divide(cohort_pivot.iloc[:,0], axis=0)

cohort_retention.head()

cohort_retention = cohort_retention.fillna(0)

cohort_retention = cohort_retention.round(4)

cohort_retention.head()

cohort_retention.to_csv("cohort_retention.csv")

